# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_data_transf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_data_transf.proto',
  package='data_transf',
  serialized_pb=_b('\n\x15sim_data_transf.proto\x12\x0b\x64\x61ta_transf\"o\n\tData_dump\x12+\n\noscillator\x18\x01 \x03(\x0b\x32\x17.data_transf.Oscillator\x12\x35\n\x0fsaddle_t_and_id\x18\x02 \x03(\x0b\x32\x1c.data_transf.Saddle_t_and_id\"!\n\nOscillator\x12\x13\n\x07reset_t\x18\x01 \x03(\x01\x42\x02\x10\x01\"6\n\x0fSaddle_t_and_id\x12\x11\n\tsaddle_id\x18\x01 \x01(\t\x12\x10\n\x08saddle_t\x18\x02 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATA_DUMP = _descriptor.Descriptor(
  name='Data_dump',
  full_name='data_transf.Data_dump',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oscillator', full_name='data_transf.Data_dump.oscillator', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='saddle_t_and_id', full_name='data_transf.Data_dump.saddle_t_and_id', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=149,
)


_OSCILLATOR = _descriptor.Descriptor(
  name='Oscillator',
  full_name='data_transf.Oscillator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reset_t', full_name='data_transf.Oscillator.reset_t', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=184,
)


_SADDLE_T_AND_ID = _descriptor.Descriptor(
  name='Saddle_t_and_id',
  full_name='data_transf.Saddle_t_and_id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='saddle_id', full_name='data_transf.Saddle_t_and_id.saddle_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='saddle_t', full_name='data_transf.Saddle_t_and_id.saddle_t', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=240,
)

_DATA_DUMP.fields_by_name['oscillator'].message_type = _OSCILLATOR
_DATA_DUMP.fields_by_name['saddle_t_and_id'].message_type = _SADDLE_T_AND_ID
DESCRIPTOR.message_types_by_name['Data_dump'] = _DATA_DUMP
DESCRIPTOR.message_types_by_name['Oscillator'] = _OSCILLATOR
DESCRIPTOR.message_types_by_name['Saddle_t_and_id'] = _SADDLE_T_AND_ID

Data_dump = _reflection.GeneratedProtocolMessageType('Data_dump', (_message.Message,), dict(
  DESCRIPTOR = _DATA_DUMP,
  __module__ = 'sim_data_transf_pb2'
  # @@protoc_insertion_point(class_scope:data_transf.Data_dump)
  ))
_sym_db.RegisterMessage(Data_dump)

Oscillator = _reflection.GeneratedProtocolMessageType('Oscillator', (_message.Message,), dict(
  DESCRIPTOR = _OSCILLATOR,
  __module__ = 'sim_data_transf_pb2'
  # @@protoc_insertion_point(class_scope:data_transf.Oscillator)
  ))
_sym_db.RegisterMessage(Oscillator)

Saddle_t_and_id = _reflection.GeneratedProtocolMessageType('Saddle_t_and_id', (_message.Message,), dict(
  DESCRIPTOR = _SADDLE_T_AND_ID,
  __module__ = 'sim_data_transf_pb2'
  # @@protoc_insertion_point(class_scope:data_transf.Saddle_t_and_id)
  ))
_sym_db.RegisterMessage(Saddle_t_and_id)


_OSCILLATOR.fields_by_name['reset_t'].has_options = True
_OSCILLATOR.fields_by_name['reset_t']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
